version: '3.8'
services:
  frontend:
    build:
      context: ./client
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - net
  backend:
    build: ./server
    ports:
      - "8080:8080"
   
    networks:
      - net
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatgpt

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - net

networks:
  net:
    driver: bridge